### PR TITLE
Ilragazzo patch 1

### PR DESCRIPTION
**Pull request by ilragazzo**
this will merge the GUI in to master, every body chill with that?

### CODE REVIEW

**Comment by troymaloney** [comment]
Let's do it

**Comment by iye1** [comment]
Its not functional, I'd say wait on pulling it

**Comment by ilragazzo** [comment]
So i just cloned this branch into an entirely new directory and ran it. It works on my x86 machines running 18.04 ubuntu but not my ARM raspberry pi running Rasbian Raspbian 9.4
Ran in spyder 3.2.6 with python 3.6.6

I think this is a library dependency issue.

**Comment by ilragazzo** [comment]
Fixed datetime string to float bug,  Please try running again so we can merge this.

**Comment by iye1** [comment]
Remove the GUI stuff from the branch and we're good, its not ready yet

**Pull request merged**
